# Generated by Django 2.2 on 2020-07-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='detailed_description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Подробное описание'),
        ),
    ]
